### ISSUE TITLE
Simple switch throws on assignment values to bool variable in Egress

### ISSUE THREAD

**Issue by xenerizes** [p4lang/behavioral-model#629] opened 2018-07-18 14:56 UTC
Hello All,

I was performing some experiments with P4 on simple switch target with v1model, when an error occurred (right after the start):
```sh
Calling target program-options parser
simple_switch: P4Objects.cpp:291: void bm::P4Objects::build_expression(const Json::Value&, bm::Expression*, bm::P4Objects::ExprType*): Assertion `typeL == typeR' failed.
Aborted
```
I am on d5ddf82, but newer commits in master give the same output.

Not sure where else the problem remains, but that the following code 
```p4
// My custom meta
struct meta {
    bool cond;
}

/* <...> */

control EgressImpl (...) {
    // In action:
    if (complex cond) {
        meta.cond = false;
        meta.cond = true;
    }
}
```
doesn't work in Egress. I've tried some variants, looks like parser and ingress work well.

P4 program and generated json can be found [here](https://gist.github.com/xenerizes/49a5a61a25c001aea1d6414d8ddcd8e6).

**Comment by antoninbas** [comment] 2018-07-18 20:30
This is probably a compiler bug, even though it's difficult to say without the generated JSON file. Would you mind attaching it to this issue?

**Comment by xenerizes** [comment] 2018-07-19 07:55
@antoninbas I appended a link to my original comment. 

I've tried to reduce my program and found out that actions like [this](https://gist.github.com/xenerizes/49a5a61a25c001aea1d6414d8ddcd8e6#file-bug-p4-L37) lead to the same error in Ingress too. With simple conditions without structs (like `true`, `1 != 5`) or without boolean variable assignment everything is ok.

**Comment by antoninbas** [comment] 2018-07-19 18:26
This is indeed a compiler bug. I filed an issue with p4c: https://github.com/p4lang/p4c/issues/1412

**Comment by xenerizes** [comment] 2018-07-20 10:39
If so, I suppose, this issue can be closed

**Comment by antoninbas** [comment] 2018-07-20 17:03
There is no harm in keeping this open until the issue is fixed in the compiler

**Closed** 2018-08-23 18:06 UTC
