### ISSUE TITLE
Error when making behavioral-model

### ISSUE THREAD

**Issue by Gxch2018** [p4lang/behavioral-model#929] opened 2020-07-25 05:32 UTC
Hi，all：
the error is ：

_imp.o src/pi_counter_imp.o src/pi_meter_imp.o src/pi_learn_imp.o src/pi_mc_imp.o src/pi_clone_imp.o src/common.o src/action_helpers.o src/direct_res_spec.o src/group_selection.o src/device_state.o
ar: `u' modifier ignored since `D' is the default (see `U')
libtool: link: ranlib .libs/libbmpi.a
libtool: link: ( cd ".libs" && rm -f "libbmpi.la" && ln -s "../libbmpi.la" "libbmpi.la" )
make[2]: Leaving directory '/home/sdn/behavioral-model/PI'
Making all in targets
make[2]: Entering directory '/home/sdn/behavioral-model/targets'
Making all in simple_router
make[3]: Entering directory '/home/sdn/behavioral-model/targets/simple_router'
depbase=`echo simple_router.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -DHAVE_CONFIG_H -I. -I../..  -I../../include                           -I../../include                           -isystem../../third_party/jsoncpp/include                           -isystem../../third_party/spdlog  -Wall -Wextra -pthread -O0 -g -std=c++11 -MT simple_router.o -MD -MP -MF $depbase.Tpo -c -o simple_router.o simple_router.cpp &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo primitives.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -DHAVE_CONFIG_H -I. -I../..  -I../../include                           -I../../include                           -isystem../../third_party/jsoncpp/include                           -isystem../../third_party/spdlog  -Wall -Wextra -pthread -O0 -g -std=c++11 -MT primitives.o -MD -MP -MF $depbase.Tpo -c -o primitives.o primitives.cpp &&\
mv -f $depbase.Tpo $depbase.Po
/bin/bash ../../libtool  --tag=CXX   --mode=link g++ -Wall -Wextra -pthread -O0 -g -std=c++11   -o simple_router simple_router.o primitives.o ../../src/bm_runtime/libbmruntime.la ../../src/bm_sim/libbmsim.la ../../src/bf_lpm_trie/libbflpmtrie.la ../../thrift_src/libruntimestubs.la ../../src/BMI/libbmi.la ../../third_party/jsoncpp/libjson.la -lboost_system -lthrift -lboost_program_options -lboost_filesystem -lboost_thread -ldl -lpcap -lgmp -lJudy -lnanomsg 
libtool: link: g++ -Wall -Wextra -pthread -O0 -g -std=c++11 -o .libs/simple_router simple_router.o primitives.o  ../../src/bm_runtime/.libs/libbmruntime.a ../../src/bm_sim/.libs/libbmsim.a ../../src/bf_lpm_trie/.libs/libbflpmtrie.a ../../thrift_src/.libs/libruntimestubs.so ../../src/BMI/.libs/libbmi.a ../../third_party/jsoncpp/.libs/libjson.a -lboost_system -lthrift -lboost_program_options -lboost_filesystem -lboost_thread -ldl -lpcap -lgmp -lJudy -lnanomsg -pthread
../../src/bm_sim/.libs/libbmsim.a(options_parse.o): In function `bm::OptionsParser::parse(int, char**, bm::TargetParserIface*, std::ostream&)':
/home/sdn/behavioral-model/src/bm_sim/options_parse.cpp:93: undefined reference to `boost::program_options::options_description::options_description(std::string const&, unsigned int, unsigned int)'
../../src/bm_sim/.libs/libbmsim.a(options_parse.o): In function `boost::program_options::validation_error::validation_error(boost::program_options::validation_error::kind_t, std::string const&, std::string const&, int)':
/usr/include/boost/program_options/errors.hpp:373: undefined reference to `boost::program_options::validation_error::get_template(boost::program_options::validation_error::kind_t)'
/usr/include/boost/program_options/errors.hpp:373: undefined reference to `boost::program_options::error_with_option_name::error_with_option_name(std::string const&, std::string const&, std::string const&, int)'
../../src/bm_sim/.libs/libbmsim.a(options_parse.o): In function `boost::program_options::variables_map::operator[](std::string const&) const':
/usr/include/boost/program_options/variables_map.hpp:155: undefined reference to `boost::program_options::abstract_variables_map::operator[](std::string const&) const'
../../src/bm_sim/.libs/libbmsim.a(options_parse.o): In function `boost::program_options::basic_command_line_parser<char>::basic_command_line_parser(int, char const* const*)':
/usr/include/boost/program_options/detail/parsers.hpp:43: undefined reference to `boost::program_options::detail::cmdline::cmdline(std::vector<std::string, std::allocator<std::string> > const&)'
../../src/bm_sim/.libs/libbmsim.a(options_parse.o): In function `std::vector<std::string, std::allocator<std::string> > boost::program_options::to_internal<std::string>(std::vector<std::string, std::allocator<std::string> > const&)':
/usr/include/boost/program_options/detail/convert.hpp:79: undefined reference to `boost::program_options::to_internal(std::string const&)'
../../src/bm_sim/.libs/libbmsim.a(options_parse.o):(.data.rel.ro._ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_15program_options16validation_errorEEEEE[_ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_15program_options16validation_errorEEEEE]+0x38): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::string const&) const'
../../src/bm_sim/.libs/libbmsim.a(options_parse.o):(.data.rel.ro._ZTVN5boost16exception_detail19error_info_injectorINS_15program_options16validation_errorEEE[_ZTVN5boost16exception_detail19error_info_injectorINS_15program_options16validation_errorEEE]+0x30): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::string const&) const'
../../src/bm_sim/.libs/libbmsim.a(options_parse.o):(.data.rel.ro._ZTVN5boost15program_options11typed_valueISt6vectorISsSaISsEEcEE[_ZTVN5boost15program_options11typed_valueISt6vectorISsSaISsEEcEE]+0x38): undefined reference to `boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::string, std::allocator<std::string> > const&, bool) const'
../../src/bm_sim/.libs/libbmsim.a(options_parse.o):(.data.rel.ro._ZTVN5boost15program_options11typed_valueImcEE[_ZTVN5boost15program_options11typed_valueImcEE]+0x38): undefined reference to `boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::string, std::allocator<std::string> > const&, bool) const'
../../src/bm_sim/.libs/libbmsim.a(options_parse.o):(.data.rel.ro._ZTVN5boost15program_options11typed_valueIicEE[_ZTVN5boost15program_options11typed_valueIicEE]+0x38): undefined reference to `boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::string, std::allocator<std::string> > const&, bool) const'
../../src/bm_sim/.libs/libbmsim.a(options_parse.o):(.data.rel.ro._ZTVN5boost15program_options11typed_valueISscEE[_ZTVN5boost15program_options11typed_valueISscEE]+0x38): undefined reference to `boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::string, std::allocator<std::string> > const&, bool) const'
../../src/bm_sim/.libs/libbmsim.a(options_parse.o):(.data.rel.ro._ZTVN5boost15program_options11typed_valueISt6vectorIN2bm9interfaceESaIS4_EEcEE[_ZTVN5boost15program_options11typed_valueISt6vectorIN2bm9interfaceESaIS4_EEcEE]+0x38): undefined reference to `boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::string, std::allocator<std::string> > const&, bool) const'
../../src/bm_sim/.libs/libbmsim.a(options_parse.o):(.data.rel.ro._ZTVN5boost15program_options20invalid_option_valueE[_ZTVN5boost15program_options20invalid_option_valueE]+0x30): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::string const&) const'
../../src/bm_sim/.libs/libbmsim.a(options_parse.o):(.data.rel.ro._ZTVN5boost15program_options16validation_errorE[_ZTVN5boost15program_options16validation_errorE]+0x30): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::string const&) const'
../../src/bm_sim/.libs/libbmsim.a(options_parse.o): In function `boost::program_options::typed_value<std::vector<std::string, std::allocator<std::string> >, char>::name() const':
/usr/include/boost/program_options/detail/value_semantic.hpp:19: undefined reference to `boost::program_options::arg'
../../src/bm_sim/.libs/libbmsim.a(options_parse.o): In function `boost::program_options::typed_value<unsigned long, char>::name() const':
/usr/include/boost/program_options/detail/value_semantic.hpp:19: undefined reference to `boost::program_options::arg'
../../src/bm_sim/.libs/libbmsim.a(options_parse.o): In function `boost::program_options::typed_value<int, char>::name() const':
/usr/include/boost/program_options/detail/value_semantic.hpp:19: undefined reference to `boost::program_options::arg'
../../src/bm_sim/.libs/libbmsim.a(options_parse.o): In function `boost::program_options::typed_value<std::string, char>::name() const':
/usr/include/boost/program_options/detail/value_semantic.hpp:19: undefined reference to `boost::program_options::arg'
../../src/bm_sim/.libs/libbmsim.a(options_parse.o): In function `boost::program_options::typed_value<std::string, char>::xparse(boost::any&, std::vector<std::string, std::allocator<std::string> > const&) const':
/usr/include/boost/program_options/detail/value_semantic.hpp:167: undefined reference to `boost::program_options::validate(boost::any&, std::vector<std::string, std::allocator<std::string> > const&, std::string*, int)'
../../src/bm_sim/.libs/libbmsim.a(options_parse.o): In function `boost::program_options::typed_value<std::vector<bm::interface, std::allocator<bm::interface> >, char>::name() const':
/usr/include/boost/program_options/detail/value_semantic.hpp:19: undefined reference to `boost::program_options::arg'
../../src/bm_sim/.libs/libbmsim.a(options_parse.o): In function `void boost::program_options::validate<std::string, char>(boost::any&, std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<std::string, std::allocator<std::string> >*, int)':
/usr/include/boost/program_options/detail/value_semantic.hpp:146: undefined reference to `boost::program_options::validate(boost::any&, std::vector<std::string, std::allocator<std::string> > const&, std::string*, int)'
/usr/include/boost/program_options/detail/value_semantic.hpp:150: undefined reference to `boost::program_options::invalid_option_value::invalid_option_value(std::string const&)'
../../src/bm_sim/.libs/libbmsim.a(options_parse.o): In function `void boost::program_options::validate<unsigned long, char>(boost::any&, std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, unsigned long*, long)':
/usr/include/boost/program_options/detail/value_semantic.hpp:92: undefined reference to `boost::program_options::invalid_option_value::invalid_option_value(std::string const&)'
../../src/bm_sim/.libs/libbmsim.a(options_parse.o): In function `void boost::program_options::validate<int, char>(boost::any&, std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, int*, long)':
/usr/include/boost/program_options/detail/value_semantic.hpp:92: undefined reference to `boost::program_options::invalid_option_value::invalid_option_value(std::string const&)'
../../src/bm_sim/.libs/libbmsim.a(options_parse.o): In function `void boost::program_options::validate<bm::interface, char>(boost::any&, std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<bm::interface, std::allocator<bm::interface> >*, int)':
/usr/include/boost/program_options/detail/value_semantic.hpp:150: undefined reference to `boost::program_options::invalid_option_value::invalid_option_value(std::string const&)'
../../src/bm_sim/.libs/libbmsim.a(options_parse.o):(.data.rel.ro._ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_15program_options20invalid_option_valueEEEEE[_ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_15program_options20invalid_option_valueEEEEE]+0x38): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::string const&) const'
../../src/bm_sim/.libs/libbmsim.a(options_parse.o):(.data.rel.ro._ZTVN5boost16exception_detail19error_info_injectorINS_15program_options20invalid_option_valueEEE[_ZTVN5boost16exception_detail19error_info_injectorINS_15program_options20invalid_option_valueEEE]+0x30): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::string const&) const'
collect2: error: ld returned 1 exit status
Makefile:383: recipe for target 'simple_router' failed
make[3]: *** [simple_router] Error 1
make[3]: Leaving directory '/home/sdn/behavioral-model/targets/simple_router'
Makefile:378: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/sdn/behavioral-model/targets'
Makefile:454: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/sdn/behavioral-model'
Makefile:384: recipe for target 'all' failed
make: *** [all] Error 2

what should I to avoid this error？thanks

**Comment by antoninbas** [comment] 2020-07-28 02:05
This seems to be a duplicate of https://github.com/p4lang/behavioral-model/issues/868.

You will need to provide more information for us to help: Linux distribution, compiler & compiler version, version of boost libraries, how did you install the dependencies

**Comment by shobhitkumargupta** [comment] 2021-10-05 13:00
Please use the below script "p4c and behavioral module Zero touch provisioning" to install the Behavioral module along with p4c compiler - 
https://github.com/shobhitkumargupta/shobhitkumargupta/commits/main

**Comment by Gxch2018** [comment] 2022-09-01 00:03
您的来信我已收到，没有发错。我会尽快给您回复。

**Comment by Gxch2018** [comment] 2023-03-01 00:02
您的来信我已收到，没有发错。我会尽快给您回复。

**Comment by Gxch2018** [comment] 2023-05-21 00:26
您的来信我已收到，没有发错。我会尽快给您回复。

**Closed** 2023-05-21 00:26 UTC
