### ISSUE TITLE
simple_switch_grpc not compiling

### ISSUE THREAD

**Issue by mohammedelazzab** [p4lang/behavioral-model#925] opened 2020-07-17 17:54 UTC
I an trying to compile the simple_switch_grpc with thrift support. I run the following commands but make fails. Iam using the latest behavioral-model code on github.

`~/behavioral-model/targets/simple_switch_grpc$ ./configure 'CXXFLAGS=-O0 -g' --with-thrift --with-grpc --with-pi`

The error is :
```
~/behavioral-model/targets/simple_switch_grpc$ make 
make  all-recursive
make[1]: Entering directory '/home/simo/behavioral-model/targets/simple_switch_grpc'
Making all in .
make[2]: Entering directory '/home/simo/behavioral-model/targets/simple_switch_grpc'
depbase=`echo switch_runner.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/sh ./libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I.  -I./../../include -I./../simple_switch -I./../../PI -isystem./../../third_party/spdlog  -DWITH_THRIFT -I./../simple_switch/gen-cpp -Icpp_out -Igrpc_out -I./cpp_out -I./grpc_out  -Wall -Wextra -pthread -g -O2 -std=c++11 -MT switch_runner.lo -MD -MP -MF $depbase.Tpo -c -o switch_runner.lo switch_runner.cpp &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I./../../include -I./../simple_switch -I./../../PI -isystem./../../third_party/spdlog -DWITH_THRIFT -I./../simple_switch/gen-cpp -Icpp_out -Igrpc_out -I./cpp_out -I./grpc_out -Wall -Wextra -pthread -g -O2 -std=c++11 -MT switch_runner.lo -MD -MP -MF .deps/switch_runner.Tpo -c switch_runner.cpp  -fPIC -DPIC -o .libs/switch_runner.o
In file included from switch_runner.cpp:49:0:
switch_runner.h:33:7: error: using typedef-name ‘grpc::Server’ after ‘class’
 class Server;
       ^
In file included from /usr/local/include/grpcpp/grpcpp.h:58:0,
                 from /usr/local/include/grpc++/grpc++.h:26,
                 from switch_runner.cpp:37:
/usr/local/include/grpcpp/server.h:26:29: note: ‘grpc::Server’ has a previous declaration here
 typedef ::grpc_impl::Server Server;
                             ^
Makefile:792: recipe for target 'switch_runner.lo' failed
make[2]: *** [switch_runner.lo] Error 1
make[2]: Leaving directory '/home/simo/behavioral-model/targets/simple_switch_grpc'
Makefile:886: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/simo/behavioral-model/targets/simple_switch_grpc'
Makefile:545: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by antoninbas** [comment] 2020-07-17 18:38
Looks like there was a change in gRPC 1.21 so if you are using a version which is more recent that this, that could explain the issue. We recommend using gRPC 1.17.2 for p4lang software, but I'll see if I can reproduce and fix the issue.

It would be useful to give us the exact gRPC version you are using.

**Comment by mohammedelazzab** [comment] 2020-07-17 19:12
My protoc version is 3.12.3. I dont know to which grpc version it corresponds

**Comment by antoninbas** [comment] 2020-07-17 19:16
```
pkg-config --modversion grpc++
```

**Comment by mohammedelazzab** [comment] 2020-07-17 19:19
it's 1.31.0-dev

**Comment by antoninbas** [comment] 2020-07-17 19:24
Since you installed the library from source (as indicated by the `-dev` suffix), you should really have installed the recommended version directly.

**Comment by mohammedelazzab** [comment] 2020-07-17 21:00
I tried with different verions , 1.17 , 1.18 , 1.20, and 1.30.x, they all gave linking errors (undefined reference to grpc_impl::..) when I compile the simple_switch_grpc except the last version (1.30.x) it gives that compilation error I showed above.

**Comment by antoninbas** [comment] 2020-07-17 21:07
it's easy to mess up your installation if you try to install multiple version in the same machine without cleaning up properly. Also make sure that you run `sudo ldconfig` after installation.

we make sure that 1.17 works as part of CI testing, which is why it is the recommended version to use.

**Comment by antoninbas** [comment] 2020-07-18 04:03
I am merging a fix for this. I still recommend using 1.17.2

**Closed** 2020-07-18 04:03 UTC
