### ISSUE TITLE
simple_switch_CLI cannot be properly executed when a non-standard prefix is specified during ./configure

### ISSUE THREAD

**Issue by vgurevich** [p4lang/behavioral-model#92] opened 2016-03-20 18:31 UTC
I tried to run ./configure with a non-standard prefix, e.g.

./configure prefix=/tmp/my_install

While make, "make check" and "make install" succeeded, simple_switch_CLI could not find runtime_CLI python module. 

The reason is, runtime_CLY.py* got installed in $(prefix)/lib/python2.7/site-packages, but then this directory is not configured to become a part of PYTHONPATH

**Comment by antoninbas** [comment] 2016-03-21 17:04
Fixed by b77e968ab6dc1853d20182b90bd78e5430c9e89a

**Comment by antoninbas** [comment] 2016-03-21 17:06
I incorrectly labeled this as a bug.
This is not a bug. If you use a custom prefix, it is your responsibility to update the `PYTHONPATH`, just like it is your responsibility to update the `PATH`.

**Comment by vgurevich** [comment] 2016-03-21 17:44
Hi Antonin,

I do not think this should be the customer's responsibility. The customer
should not care which language a program is written and what are the
internal pre-requisites. If "make install" succeeded, the expectation is
that no matter where the program was executed from (it doesn't have to be
in the PATH, one can simply specify full PATH to run it), it will run
correctly and find all its pre-requisites.

Thanks,
Vladimir

**Comment by antoninbas** [comment] 2016-04-14 21:45
solved in #104

**Closed by antoninbas** 2016-04-14 21:45 UTC
