### ISSUE TITLE
Hitting assert in device_mgr.cpp when trying to read table entry with direct counters

### ISSUE THREAD

**Issue by dushyantarora13** [p4lang/behavioral-model#490] opened 2017-12-11 22:41 UTC
I modified the test in targets/simple_switch_grpc/tests/test_grpc_counter.cpp to read table entry after writing them by adding the following lines after sending the WriteRequests:

```
  p4::ReadRequest read_request;
  read_request.set_device_id(device_id);
  auto read_entity = read_request.add_entities();
  auto table_entry = read_entity->mutable_table_entry();
  table_entry->set_table_id(t_id);
  table_entry->set_priority(100);
  auto match = table_entry->add_match();
  match->set_field_id(mf_id);
  auto exact = match->mutable_exact();
  exact->set_value(std::string("\x00\x00\x00\x0a", 4));

  ClientContext context;
  std::unique_ptr<grpc::ClientReader<p4::ReadResponse> > reader(
  p4runtime_stub->Read(&context, read_request));
  p4::ReadResponse read_response;
  reader->Read(&read_response);
  auto status = reader->Finish();
  EXPECT_TRUE(status.ok());
```

The code however crashes when trying to execute the read request. Here is the trace:
```
[ RUN      ] SimpleSwitchGrpcTest_Counter.CounterHit
New connection
P4Runtime SetForwardingPipelineConfig
P4Runtime Write
device_id: 3
election_id {
  low: 1
}
updates {
  type: INSERT
  entity {
    table_entry {
      table_id: 33591959
      match {
        field_id: 1
        exact {
          value: "\000\000\000\n"
        }
      }
      action {
        action {
          action_id: 16795932
        }
      }
      priority: 100
    }
  }
}
P4Runtime Write
device_id: 3
election_id {
  low: 1
}
updates {
  type: INSERT
  entity {
    table_entry {
      table_id: 33591959
      match {
        field_id: 1
        exact {
          value: "\000\000\000\005"
        }
      }
      action {
        action {
          action_id: 16795932
        }
      }
      priority: 100
    }
  }
}
P4Runtime Read
device_id: 3
entities {
  table_entry {
    table_id: 33591959
    match {
      field_id: 1
      exact {
        value: "\000\000\000\n"
      }
    }
    priority: 100
  }
}
lt-test_gtest: src/device_mgr.cpp:606: pi::fe::proto::Status pi::fe::proto::DeviceMgrImp::table_read_common(pi::fe::proto::p4_id_t, const pi::fe::proto::common::SessionTemp&, T*, Accessor) const [with T = p4::ReadResponse; Accessor = pi::fe::proto::DeviceMgrImp::table_read_one(pi::fe::proto::p4_id_t, const pi::fe::proto::common::SessionTemp&, p4::ReadResponse*) const::<lambda(p4::ReadResponse*)>; pi::fe::proto::Status = google::rpc::Status; pi::fe::proto::p4_id_t = unsigned int]: Assertion `0 && "Invalid state"' failed.
Aborted (core dumped)
```

**Comment by antoninbas** [comment] 2017-12-12 02:08
I'm going to take a look but I'm almost 100% sure that this is because you are providing a priority value for an exact match table, which I must not have expected (priority has no meaning for exact match).
I'll fix the segfault.

**Comment by antoninbas** [comment] 2017-12-12 02:12
I confirmed that the issue comes from the explicit priority. Will fix.

**Comment by dushyantarora13** [comment] 2017-12-12 02:35
Thanks for the reply Antonin! I ran the test again after removing the priority field from both my write and read requests.
```
  p4::ReadRequest read_request;
  read_request.set_device_id(device_id);
  auto read_entity = read_request.add_entities();
  auto table_entry = read_entity->mutable_table_entry();
  table_entry->set_table_id(t_id);
  auto match = table_entry->add_match();
  match->set_field_id(mf_id);
  auto exact = match->mutable_exact();
  exact->set_value(std::string("\x00\x00\x00\x0a", 4));

  ClientContext context;
  std::unique_ptr<grpc::ClientReader<p4::ReadResponse> > reader(
  p4runtime_stub->Read(&context, read_request));
  p4::ReadResponse read_response;
  reader->Read(&read_response);
  auto status = reader->Finish();
  EXPECT_TRUE(status.ok());
```
I receive 2 entities in my read_response. I was expecting a single entity since I specify the match field. Also, the table entries in the response do not have the counter_data field set. Is this expected?

**Comment by antoninbas** [comment] 2017-12-12 02:39
You should get a single entity in the response. I'll look into it once I fix the original issue.
Support for `counter_data` has not been added yet.

**Comment by antoninbas** [comment] 2017-12-12 02:58
@dushyantarora13 regarding the number of entries returned, I just remembered that I have yet to implement filtering on the match key for table read (see this TODO: https://github.com/p4lang/PI/blob/master/proto/frontend/src/device_mgr.cpp#L674). The only thing supported right now is "read all tables" vs "read a single table".

**Comment by dushyantarora13** [comment] 2017-12-12 03:11
Got it. Thanks for the reply!

**Comment by antoninbas** [comment] 2017-12-12 17:41
The original issue was fixed with https://github.com/p4lang/PI/pull/254 so I'm closing this.
Feel free to open new issues in p4lang/PI for non-implemented features if you want to track progress on them.

**Closed by antoninbas** 2017-12-12 17:41 UTC
