### ISSUE TITLE
b2b8666 has broken four p4c tests

### ISSUE THREAD

**Issue by hesingh** [p4lang/behavioral-model#862] opened 2020-02-04 02:57 UTC
The p4c tests that broke are:

     70 - bmv2/testdata/p4_14_samples/parser_value_set1.p4 (Failed)
     77 - bmv2/testdata/p4_14_samples/parser_value_set0.p4 (Failed)
     110 - bmv2/testdata/p4_14_samples/issue946.p4 (Failed)
     193 - bmv2/testdata/p4_14_samples/parser_value_set2.p4 (Failed)

Having run one failed test, this is the error:

```
hemant@ubuntu:~/int/p4c/build$ bmv2/testdata/p4_14_samples/parser_value_set0.p4.test -f
Check for  /home/hemant/int/p4c/testdata/p4_14_samples/parser_value_set0.stf
Calling target program-options parser
Parser transition mask for value set has incorrect width, expected width is 2 bytes but actual width is 1 bytes
bad json:
{
   "mask" : 0,
   "next_state" : null,
   "type" : "parse_vset",
   "value" : "pvs0"
}
```

**Comment by hesingh** [comment] 2020-02-04 03:00
@antoninbas If p4c changes are needed to support the new behavioral-model code, please let us know.

**Comment by antoninbas** [comment] 2020-02-04 17:52
The issue is the one I pointed out before: mask is `0` when it should be `null` for a PVS parser transition. I see that @mbudiu-vmw opened a PR already: https://github.com/p4lang/p4c/pull/2183. With the current JSON, simple_switch will crash if you try to send traffic through.

**Comment by antoninbas** [comment] 2020-02-04 17:57
Closing this as it is not an issue with bmv2.

**Closed by antoninbas** 2020-02-04 17:57 UTC
