### ISSUE TITLE
 ipv6 address for addHost( ) 

### ISSUE THREAD

**Issue by djshah19** [p4lang/behavioral-model#621] opened 2018-06-14 19:57 UTC
Hello,

I currently want to use mininet API to create a custom network topology. And I want every host to be configured as ipv6 address after I start the
network topology.

My question is: in mininet addHost( ) API, can I pass in ipv6 address instead of ipv4 address? If I can, could you please give me some hint about how I can do it? I tried couple times but looks like addHost( ) can not do so.

Many thanks,
Dhwan

**Comment by antoninbas** [comment] 2018-06-14 23:58
Duplicate of https://github.com/p4lang/tutorials/issues/177
This looks like a question for the Mininet community. Based on the Mininet code, I am not sure the `ip` parameter of `addHost` will work with IPv6 addresses. But I believe Mininet lets you execute arbitrary shell commands in each host, so you may want to look into that and try executing your own `ifconfig` command to assign an IPv6 address to each host.

**Closed by antoninbas** 2018-06-14 23:58 UTC
