### ISSUE TITLE
Does P4 runtime support the write operation to the register array in the data plane ?

### ISSUE THREAD

**Issue by Johnny-dai-git** [p4lang/behavioral-model#1142] opened 2022-09-19 21:35 UTC
Hi, 

I am trying to do some reset/write operation to the register array via the controller. However, I can not find the API support such behavior. It seems that the protobuf have defination for such behavior. Is that possible for me to reset the register array in the data plane periodically without my manually configuration via CLI ?

Best Regards,

**Comment by antoninbas** [comment] 2022-09-19 21:37
Duplicate of https://github.com/p4lang/PI/issues/376

**Closed by antoninbas** 2022-09-19 21:37 UTC
