### ISSUE TITLE
Seeing Help for Parse TCP Option 

### ISSUE THREAD

**Issue by qq995002966** [p4lang/behavioral-model#339] opened 2017-04-25 07:58 UTC
_Maybe this request shouldn't be posted here,while this repository is so active I really hope some one can do me a favor._ 

For some reason I want to parse TCP Options using p4 , but it seems that there is no such a helpful code to reference in this repository and P4 spc.
Could you please give me some advise how to parse TCP Options using p4?

Thanks. John.

**Comment by antoninbas** [comment] 2017-04-25 16:59
This is a duplicate of the issue you opened in the tutorials repo (https://github.com/p4lang/tutorials/issues/26).
Please refrain from posting duplicates.

**Closed by antoninbas** 2017-04-25 16:59 UTC
