### ISSUE TITLE
simple_switch_grpc is not make by default

### ISSUE THREAD

**Issue by qin-nz** [p4lang/behavioral-model#487] opened 2017-12-09 13:54 UTC
I try to use `--with-pi` to configure in the root directory and then `make ` it.
I notice simple_switch_grpc is not make.

To make it, I have entry directory `targets/simple_switch_grpc` and run 
```
./autogen.sh && ./configure && make
```

It is by design?

**Comment by antoninbas** [comment] 2017-12-11 02:13
Yes that's by design. Ideally simple_switch_grpc would be a separate repository. The bmv2 implementation of PSA, which should come some time in 2018, will be in its own repo. simple_switch_grpc is kind of a temporary solution while we wait for that and is simply a version of simple_switch which supports P4 Runtime.
The top-level Makefile could build simple_switch_grpc I guess, but I wanted to avoid having to add yet another configure flag and I wanted to keep it as its own "project" since it will eventually be replaced by PSA in a separate repository.

**Closed** 2017-12-11 03:11 UTC
