### ISSUE TITLE
mac_learn without using generate_digest

### ISSUE THREAD

**Issue by ranouch** [p4lang/behavioral-model#613] opened 2018-05-31 12:32 UTC
hi,
I have an issue to code a mac_learn action in the P4 switch saving new source addresses IN the switch (so, without using the generate_digest action because it saves in the receiver).
Where can I save the addresses? With which action or function? Can I use a C code in .p4 file?
I'm going to create rules dynamically in a table from any package using p4 langage
how to extract information from a package and automatically builds rules from these information in another array??????
please, can your help me?
Greetings,
rania

**Comment by antoninbas** [comment] 2018-05-31 16:39
Closing this issue as it seems like an exact duplicate of https://github.com/p4lang/PI/issues/365

**Closed by antoninbas** 2018-05-31 16:39 UTC
