### ISSUE TITLE
simple_switch_grpc can not take control of the interface

### ISSUE THREAD

**Issue by Johnny-dai-git** [p4lang/behavioral-model#1136] opened 2022-09-01 20:24 UTC
HI, everyone

I have encounter a problem while using the simple_switch_grpc. I intended to change a bare metal machine into p4 switch using simple_switch_grpc. 

I follow this link to compile my code: https://github.com/p4lang/behavioral-model/blob/main/targets/simple_switch_grpc/README.md 

The platform I am working on is ubuntu 20.04, kernel version 5.15.0-46-generic.

I can run the simple_switch_grpc with --no-p4 options successfully. In this case, all the packet controlled by the simple_swtich_grpc should be dropped. However,  while I test between two machines, it is not the case. 

For example,  if machine 1 is running simple_swtich_grpc and controlling its interface 1. Meanwhile this interface are connecting to the interface 2 on the machine 2. 

There should be no packets go through the interface 1. However, the ping between these two interfaces are successful. 

It seems that the simple_switch_grpc does not control the packet and all these packets does not reroute to the simple_switch_grpc process. 

Anything I can do to solve this problem ?

Best Regards,

**Comment by antoninbas** [comment] 2022-09-01 20:41
you need to make sure the interfaces connected to bmv2 don't have IP addresses assigned to them

**Comment by antoninbas** [comment] 2022-09-02 19:42
In your first post, you wrote:
> There should be no packets go through the interface 1. However, the ping between these two interfaces are successful.

In your new post, you wrote:
> However, I can observe the packet come in the interface enp1s0f2 but i never seen any packet go out of enp1s0f3.

Don't these 2 things mean the opposite? Please clarify what the problem is.

* When packets bypass simple_switch, the most common explanations are: IP addresses are assigned to the interfaces, IP forwarding is enabled.
* If simple_switch is processing the packets but not the way you expect, you just need to look at the logs (use `--log-console`) to figure out what's going on.

> One more thing, is there a way to luach the simple_switch_grpc with p4.json
without transmite with the controller ?

Yes but it's not really recommended: don't use `-no-p4` and provide the path to JSON as a positional argument to `simple_switch_grpc`.

**Closed as not planned** 2022-09-02 20:23 UTC
