### ISSUE TITLE
How to implement custom extern functions in simple_switch target

### ISSUE THREAD

**Issue by degaetanoa** [p4lang/behavioral-model#803] opened 2019-07-23 08:02 UTC
Hello everyone,
I'm using bmv2 simple_switch in my master thesis and I need a custom extern function in order to implement a feature that involves a header and the payload.  I've searched around some tips, but actually is not very well documented.
I will try to keep it as general as possible, it could be useful also for other people.
What I have understood:
-I write the extern function;
-I recall the function in my .p4;
-I need to add the declaration of my extern somewhere in bmv2 sources (maybe simple_switch sources), in this way v1model becomes new_v1model;
What I have not understood:
-Does p4c need flags/declarations/changes?
-Is there a folder where my extern function must be?
-In which source file I have to declare my function?
-Is the extern function compiled directly by simple_switch at runtime or I need a previous step?(I mean I have a .c function, what happens when I start the switch and the extern is invoked? I imagine that the switch will look for the executable)
-What can I pass to the extern function? (headers, payload, the entire packet, metadata, ecc.)
-What can the extern function return to the pipeline?
-Is there any restriction on what an external function can do?

I'm a little confused. 
If you think that I need more information other than the questions above and you want to add something else, thank you in advance.

**Comment by drobinkent** [comment] 2019-11-08 21:22
Have you found the steps? If yes, can you please share the whole process?

**Comment by degaetanoa** [comment] 2019-11-08 21:43
No sorry, I have directly modified bmv2 device manager. Probably they don't want to share this type of information because is contrast with their interest. In the same way, bmv2 performances are not optimized. There are locking queues, gazillions of thread creation and other absurd things. If you don't want to modify source files, I suggest you to avoid bmv2: there are too many people working on that, they don't share information even among them so we have no hope.

**Comment by degaetanoa** [comment] 2019-11-09 08:53
It's funny and sad at the same time, because in about 5 months nobody has answered me and when a critique has been written, suddenly, I've got an answer. I wanted to modify all the code if necessary, but there aren't enough comments into it or documentation. When I've opened this issue I had enough time, but without some hints it's really a mess. I've done it in my way and I've also written an ad hoc bridge with comparison purposes. I would have liked to stay as standard as possible to make my work useful in future, but it hasn't been possible. There are contradictory issues right here on GitHub, sometimes there are developers asking information one to the other, passing the message that even them have not a complete sight on the project. Bmv2 is a huge guy and I was trying to implement it with Intel SGX, an even bigger project. I've read more than half of the source files, but understanding code written by others is not always an easy task. I would have liked to get little help, anyway the previous comment is the demonstration that this topic is an open one and it is not crystal clear. I would suggest to improve comments into the code or documentation or just give an exhaustive answer once and for all. It could take lot of time, but if I do it myself it's useful only for me and maybe is not even the right way to do it because I don't have the entire view of the project. How many people are doing the wrong thing because of lack of information? Sharing information is the first step to make a tool widespread and established, this is my opinion. 
Have a nice day at work and good luck to drobinkent

**Comment by jnfoster** [comment] 2019-11-23 06:34
@degaetanoa,

I'm sorry you didn't get a timely response from the community and became frustrated. I'm not quite sure why we missed your note. Speaking for myself, while I'm not a core Bmv2 developer, I do try to help out with answering questions on the many p4lang repositories as I can. But I was on vacation in late July and traveling for work much of August. I didn't realize this issue was open until many weeks had passed and there was another followup.

I suspect the main reason your post didn't get a quick response was that your question was on a topic that has been addressed previously. It would have been easier for an expert to jump in and help, if you'd explained what aspects of @antoninbas's detailed response to #697 you found unclear, or where specifically you were stuck with your own implementation. Vague and broad questions (e.g., "I'm a little confused" and "If you think that I need more information") are much harder to respond to than detailed and focused ones.

Adding new externs to Bmv2 and P4c is a non-trivial task. But I think it is one that a good CS master's student should be able to accomplish in a reasonable timeframe. For example, last spring, @jafingerhut and I, neither of whom were core Bmv2 developers, advised a group of students who were new to P4 or Bmv2 at the beginning of the project. It did take them most of a semester to get up to speed and familiarize themselves with the codebase before they were able to contribute initial implementations of the PSA pipeline and many of its externs.

Finally, a few thoughts about how to ask effective questions in open-source communities. It's generally a good idea to ask your question as succinctly as possible (to respect people's time) while also providing sufficient detail (so they can help you take the next step). Small things like using proper spelling and grammar and paying attention to formatting can increase the likelihood of a timely and helpful response.

Your original question was fairly broad. I'm still not sure exactly what you were asking, but I think you wanted an endorsement of a high-level plan for implementing new externs. There are some parts of your plan that sound fine to me, some parts that are unclear, and some parts that contain mistakes. So it would take a long time for someone to work through your note and write a good response. Ideally this kind of plan is something your master's advisor would have worked out with you at an earlier stage of the project. It would have been better, in my humble opinion, to describe precisely where you were stuck with your implementation and ask for help getting past that barrier. Given such a question, an expert could quickly jump in and provide assistance. And it would also show you'd made an investment in understanding the system sufficiently well and had gotten a basic develop-compile-test-debug loop running, so you could ask thoughtful question. 

Lastly, unfounded allegations ("they don't want to share this type of information because is contrast with their interest") and words that could be interpreted in a negative way ("absurd" and "it's really a mess") are not things I would like to see in the P4 community. You may not think highly of Bmv2 or the state of its documentation. But a human being wrote that code and takes pride in their work. Please think about how you'd feel if the roles were reversed and try to treat everyone with a basic level of respect.

**Comment by jnfoster** [comment] 2019-11-23 06:34
Closing this as it's a duplicate of #697

**Closed by jnfoster** 2019-11-23 06:34 UTC
