### ISSUE TITLE
make error Problem

### ISSUE THREAD

**Issue by Wasdns** [p4lang/behavioral-model#199] opened 2016-09-25 11:04 UTC
Hi, friends. I'm new P4...I'm sorry to take your time to look my problem.

When I followed the steps of **Building the code**:
```
1. ./autogen.sh
2. ./configure
3. make
```
It turns out:
```
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
make[3]: *** [packet.lo] Error 1
make[3]: Leaving directory `/home/wasdns/behavioral-model/src/bm_sim'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/home/wasdns/behavioral-model/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/wasdns/behavioral-model'
make: *** [all] Error 2
```
I tried to fix the problem. I found the place: /behavioral-model/src/bm_sim/packet.cpp
I changed the content : 
```
#include </home/wasdns/behavioral-model/include/bm/bm_sim/packet.h>
```
run `gcc packet.cpp`, it solved "header file not found" problem, but it turns out a lot of other problems:
```
······
/home/wasdns/behavioral-model/include/bm/bm_sim/phv.h:95:32:   required from here
/usr/include/c++/4.8/bits/stl_construct.h:83:7: error: use of deleted function ‘bm::Header::Header(const bm::Header&)’
       ::new(static_cast<void*>(__p)) _T1(__value);
       ^
In file included from /home/wasdns/behavioral-model/include/bm/bm_sim/phv.h:38:0,
                 from /home/wasdns/behavioral-model/include/bm/bm_sim/phv_source.h:26,
                 from /home/wasdns/behavioral-model/include/bm/bm_sim/packet.h:39,
                 from packet.cpp:21:
/home/wasdns/behavioral-model/include/bm/bm_sim/headers.h:259:3: error: declared here
   Header(const Header &other) = delete;
   ^
```
It must be wrong. But I have no idea about it. I added "sudo" but it didn't work.

Thank you for watching my problem !

**Comment by antoninbas** [comment] 2016-09-25 20:33
You mention a "header file not found problem" but I don't see it in the error output. Did you forget to include some of it?
Most of the times I see a `g++: internal compiler error: Killed` message is when I run out of memory, so you may want to check that this is not what is happening here.

**Comment by Wasdns** [comment] 2016-09-26 00:36
@antoninbas Thank you!  But I still have no idea...
The content of packet.cpp was:
```
#include <bm/bm_sim/packet.h>
```
It turned out "header file not found" when I try to gcc it. So I changed it to 
```
#include </home/wasdns/behavioral-model/include/bm/bm_sim/packet.h>
```
It solved my problem.

**Comment by Wasdns** [comment] 2016-09-26 00:50
@antoninbas Thank you for your great help. By the way, can you help me another problem? I'm sorry about that.

I have a problem when I take the steps of p4factory ReadMe **Integration with Mininet**.
I followed the steps:
```
cd p4factory/targets/simple_router/
make bm
./run_demo.bash
```
And I opened a new terminal, and tried:
```
./run_add_demo_entries.bash
```
but it falied:
```
ImportError: cannot import name TFrozenDict
ImportError: cannot import name TFrozenDict
ImportError: cannot import name TFrozenDict
ImportError: cannot import name TFrozenDict
ImportError: cannot import name TFrozenDict
ImportError: cannot import name TFrozenDict
```
I googled it, but I still cannot fixed it...

I dont know how to show you my gratitude, but I really appriciate of what you have done to me.

**Comment by antoninbas** [comment] 2016-09-26 17:32
I'm glad you made it work. But you should definitely not have to change this manually like this. The first include path should work fine; this error has never shown in our regressions and no one else has reported this before. Because of lack of information, I am closing this issue and not investigating further.

**Closed by antoninbas** 2016-09-26 17:32 UTC
