### ISSUE TITLE
One Bug and How to modify the length of a field

### ISSUE THREAD

**Issue by realmanhw** [p4lang/behavioral-model#320] opened 2017-04-03 09:01 UTC
Hello! I met a problem, I want to change the length of a field, is there a method to achieve this? I define a header like this
![2017-04-03 16 14 32](https://cloud.githubusercontent.com/assets/16850492/24600806/d8bc18be-1888-11e7-9fc4-e5e22977cbd1.png),
 **pids** which I define is variable. Before I use **modify_field**, I debug it and watch the value, the value is right. But after I use **modify_field** method to modify it , no matter what src I fill in, it turns out to be all **zero**, seen the picture.
![image](https://cloud.githubusercontent.com/assets/16850492/24601265/cacf5296-188a-11e7-979a-a9cce4b43b20.png).
I have tried immediate number and metadata to be src, but the result are the same, just all zero.
My goal is to change the length of this field when the packet passes through one switch. For example,
96(bit)->64(bit)->32(bit)->64(bit)->96(bit) and the packet length also change at the same time.
like this
1111111100000000111111110000000011111111000000001111111100000000------------>
11111111000000001111111100000000----------->
1111111100000000111111110000000011111111000000001111111100000000
 How can I achieve this? Thank you.

**Comment by antoninbas** [comment] 2017-04-03 20:28
I wasn't able to reproduce this bug. I wrote a small P4 program with a VL field and `modify_field` seemed to work fine on that field (I tried with an immediate value as the source). If you insist there is a bug, please send a full P4 program (along with CLI commands) as well as some packet input we can use to reproduce this.
We do not support modifying the length of the VL field during packet length (to be more precise, modifications to your `color.total_len` field will be ignored by the deparser).  Based on the example you give, it may be better for you to use separate 32-bit headers (potentially in a stack) that you can validate / invalidate:
```
header_type color_init {
    fields {
        version_Type : 8;
        // ...
        data : 64;
    }
}
header_type pid_t {
    fields { f : 32; }
}
header color_init color;
header pid_t pids[3];
```
That's assuming some field in the `color_init` header_type tells you how many `pids` you need to extract.

I didn't see anything in the P4_16 indicating that the dynamic width of a `varbit` field can be changed by the pipeline, but maybe this will be added in the future.

**Comment by realmanhw** [comment] 2017-04-04 03:43
Then, is there a method to add or delete a field? The function I want to implement is a **variable pid** to mark the path which the packet passed. Once a packet pass through a switch, a pid will be added to the tail-end part of the packet. If I use separate pids just as your suggestion , that is pid1, pid2, pid3. Once the switch receievd a packet, it will lookup the flowtable and match a corresponding item then read the new pid to add(not just modify the content) to the packet, then the packet will be longer, and when this packet return to this switch and go back through the same path, this pid will be deleted.
just like

` pid1-->pid1,pid2-->pid1,pid2,pid3-->pid1,pid2-->pid1.`

 After I read the P4specification I didn't find the corresponding method. But I insist that we need this feature.

**Comment by antoninbas** [comment] 2017-04-04 04:16
That's why I put pid in its own header, Because it is possible to add / remove headers (or push / pop them if you use a stack), but not fields. By putting a single field in the header, you can achieve the same effect.

**Comment by realmanhw** [comment] 2017-04-04 07:50
Thanks for your advice. Is it convenient for you to show me a short example about how to push and pop a header instance. And after the packet was pushed into a stack, how do they be transmitted to the next switch?

**Comment by antoninbas** [comment] 2017-04-05 00:23
How to use push and pop is pretty straightforward and it is described in the spec. However, it can only be used if you want to push a new pid at the beginning of the header, or pop the first pid in the header. In this case, the P4 program could look like this (I am not including a full program):
```
header_type color_init {
    fields {
        version_Type : 8;
        // ...
        data : 64;
    }
}
header_type pid_t {
    fields { f : 32; }
}
header color_init color;
header pid_t pids[3];

parser start {
    extract(color);
    set_metadata(my_meta.num_pids, /* get this info from the color header */);
    return parse_pid_0;
}
parser parse_pid_0 {
    return select(my_meta.num_pids) {
        0 : ingress;
        _ : parse_pid;
    }
}
parser parse_pid {
    extract(pids[next]);
    set_metadata(my_meta.num_pids, my_meta.num_pids - 1);
    return parse_pid_0;
}

action a_push() {
    // push pid to the front
    push(pids);
    pids[0].f = /* whatever value */
}
action a_pop() {
    // remove first pid
    pop(pids);
}
```
If you need to add / remove a pid at the end (instead of the beginning), then you cannot use a stack and the program becomes more complicated.

**Comment by realmanhw** [comment] 2017-04-05 01:28
Thanks, I will try it and give you a feedback later.

**Comment by antoninbas** [comment] 2017-04-05 17:00
There is no support for using `last` in a table match key. I can open an issue to add support, but there are several important points to consider here:
- even though you are writing programs in P4_14, the community is steadily moving to P4_16; as per the P4_16 spec (http://p4.org/wp-content/uploads/2016/12/P4_16-prerelease-Dec_16.html#sec-expr-hs), `last` for header stacks will only be available in the context of a parser (and not in control flows).
- if you find yourself accessing the last element of the stack for your processing, then header stacks may not be very appropriate for what you are trying to do. The P4 header stacks are much more convenient when you only need to modify / access the front of the stack.

In the meantime, a possible workaround would be to copy `pid[last].pid` to a metadata field in a previous table, and use that metadata field in the match key. This will run on bmv2.
```
action a_copy() { modify_field(my_meta.last_pid, pid[last].pid); }
table t_copy {
    actions { a_copy; }
    default_action : copy();
}
table t {
    reads { my_meta.last_pid : exact; }
    // ...
}
```

**Comment by realmanhw** [comment] 2017-04-07 08:56
When I tried to push a new instance to the packet, I defined a new instance, 
```
header_type color_pid_t{
    fields{
        pid : 32;
    }
}
header color_pid_t pid_push[1];
```
, and **it had not been extracted in the parser(because the packet length is not enough for this instance,it is a new field I want to add to the packet, I just want to add it to the packet first and then read flowtabel and then use **modify_field()** method to change it )**. In the match-action table , I used **push(pid_push,1);**,it seems that nothing was added to packet, then I tried **add_header(pid_push[0]);**, it did work either, I think maybe array doesn't work, then I define `header color_pid_t pid_push;`and used `add_header(pid_push);` still did not work. then I tried metadata instance
```
header_type color_pid_t{
    fields{
        pid : 32;
    }
}
metadata color_pid_t metapid;
```
and applied the same method, it sitll didn't work. I read the specification(add_header):
![2017-04-07 16 46 13](https://cloud.githubusercontent.com/assets/16850492/24792723/c273481c-1bb1-11e7-9b32-4154328afe2d.png)
 In my imagination, it should work, I just do not understand why and I really need to achieve this feature, how to do?

**Comment by antoninbas** [comment] 2017-04-07 17:09
This is getting very confusing for me and I am closing this issue. If you think something is not behaving correctly or you require help with something, please open a _new_ issue and include your _entire P4 program as a file attachment_, not as screenshots.

**Closed by antoninbas** 2017-04-07 17:09 UTC
