### ISSUE TITLE
Simple_switch's Control invoking stack is wrong.

### ISSUE THREAD

**Issue by MaoJianwei** [p4lang/behavioral-model#470] opened 2017-11-20 07:25 UTC
Hi all,

As follow codes, 

I track the log-console output as the bottom,
ingress goes into callee from A, but when callee returns, callee will return to ingress's B line, and do B.

It looks like the function invoking stack is wrong.
How can it happen?

Thanks!

```

control ingress {

   callee() callee;

    apply{

    if (...) {
      callee.apply();
      do something A.....
   } else {
      if(...) {
          callee.apply();
          do another thing B....
      }
   }
   }
}

```

![qq 20171120152208](https://user-images.githubusercontent.com/12800168/33006873-06d44c2e-ce07-11e7-8698-ef3379b08550.jpg)
![qq 20171120152415](https://user-images.githubusercontent.com/12800168/33006872-062b55b0-ce07-11e7-90c6-36f60074182c.jpg)
![qq 20171120152505](https://user-images.githubusercontent.com/12800168/33006871-05dc5082-ce07-11e7-8021-ed13036ba2a5.jpg)
![qq 20171120152657](https://user-images.githubusercontent.com/12800168/33006937-4f1fdb7e-ce07-11e7-85b5-a55e11418ff6.jpg)

**Comment by antoninbas** [comment] 2017-11-20 16:38
Juts like https://github.com/p4lang/behavioral-model/issues/465, this looks like a compiler issue.

In this case it actually looks very much like a duplicate of https://github.com/p4lang/p4c/issues/986. bmv2 does not support your program because of its internal table graph representation. You cannot apply the same control twice - even in mutually-exclusive branches - if what you do after each "apply" is not exactly the same. The most recent version of the compiler should reject your program since the issue is marked as resolved. If it's not the case you may want to re-open the compiler issue and submit your program there.

**Comment by MaoJianwei** [comment] 2017-12-06 06:58
In my memory, I don't see any exposition for this 'internal table graph representation' in P4-16/14 spec, so is it a limitation just in BMv2? or in Tofino either?

Thanks.

**Comment by antoninbas** [comment] 2017-12-06 07:04
@MaoJianwei This is not the appropriate forum to discuss what Tofino can or cannot do. If you have a question about Tofino, please contact Barefoot customer engineering.

**Closed by antoninbas** 2017-12-06 07:04 UTC

**Comment by MaoJianwei** [comment] 2017-12-06 07:08
okay, thanks, so this is a special limitation for bmv2? 

In my memory, I don't see any exposition for this 'internal table graph representation' in P4-16/14 spec

**Comment by antoninbas** [comment] 2017-12-06 07:11
yes, my comment in https://github.com/p4lang/p4c/issues/457 explains why this is a limitation of the current bmv2 implementation and of the JSON representation.

**Comment by MaoJianwei** [comment] 2017-12-06 07:21
So it looks like that we can say this is a known bug for a long time in BMv2, do you have a plan to resolve it?

by refactoring bmv2 to avoid 'internal table graph representation' and some way else.

thanks.

**Comment by jafingerhut** [comment] 2017-12-06 07:30
@MaoJianwei I would say it is a known limitation in BMv2 that has existed for a long time, by choice and design, because it is considered low priority relative to many other enhancements and bugs being worked on.

**Comment by jafingerhut** [comment] 2017-12-06 09:36
Actually, I should amend my statement somewhat to say that the following program with equivalent behavior should compile:
```
if (some_condition) {
    t1_copy1.apply();
}
t2.apply();
if (!some_condition) {
    t1_copy2.apply();
}
```

**Comment by MaoJianwei** [comment] 2017-12-06 10:24
well
